[project]
name = "repl-nix-githubimporter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pypdf2>=3.0.1",
    "python-docx>=1.1.2",
    "reportlab>=4.2.5",
    "streamlit>=1.41.1",
    "trafilatura>=2.0.0",
    "twilio>=9.4.1",
]
