[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false

[logger]
level = "debug"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
showErrorDetails = true
toolbarMode = "developer"
